# Generated by Django 5.2.13 on 2026-04-11 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("strategies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20, verbose_name="الرمز")),
                (
                    "order_type",
                    models.CharField(
                        choices=[("buy", "شراء"), ("sell", "بيع")],
                        max_length=10,
                        verbose_name="نوع الأمر",
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="الحجم"
                    ),
                ),
                (
                    "entry_price",
                    models.DecimalField(
                        decimal_places=5, max_digits=15, verbose_name="سعر الدخول"
                    ),
                ),
                (
                    "exit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        max_digits=15,
                        null=True,
                        verbose_name="سعر الخروج",
                    ),
                ),
                (
                    "stop_loss",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        max_digits=15,
                        null=True,
                        verbose_name="وقف الخسارة",
                    ),
                ),
                (
                    "take_profit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        max_digits=15,
                        null=True,
                        verbose_name="جني الأرباح",
                    ),
                ),
                (
                    "pnl",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="الربح والخسارة",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("open", "مفتوحة"),
                            ("closed", "مغلقة"),
                            ("cancelled", "ملغاة"),
                            ("failed", "فشلت"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "external_ticket",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="رقم العملية الخارجي"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                ("opened_at", models.DateTimeField(verbose_name="تاريخ الفتح")),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الإغلاق"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trades",
                        to="strategies.strategy",
                        verbose_name="الاستراتيجية",
                    ),
                ),
            ],
            options={
                "verbose_name": "صفقة",
                "verbose_name_plural": "الصفقات",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="العنوان")),
                ("message", models.TextField(verbose_name="الرسالة")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("system", "نظام"),
                            ("trade", "صفقة"),
                            ("risk", "مخاطر"),
                            ("analysis", "تحليل"),
                        ],
                        default="system",
                        max_length=20,
                        verbose_name="نوع الإشعار",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="تمت القراءة"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
                (
                    "trade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="trading.trade",
                        verbose_name="الصفقة",
                    ),
                ),
            ],
            options={
                "verbose_name": "إشعار",
                "verbose_name_plural": "الإشعارات",
            },
        ),
        migrations.CreateModel(
            name="TradingAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "broker_name",
                    models.CharField(max_length=100, verbose_name="اسم الوسيط"),
                ),
                (
                    "account_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="معرف الحساب"
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[("demo", "تجريبي"), ("live", "حقيقي")],
                        default="demo",
                        max_length=10,
                        verbose_name="نوع الحساب",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="الرصيد",
                    ),
                ),
                (
                    "equity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="حقوق الملكية",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=10, verbose_name="العملة"
                    ),
                ),
                (
                    "leverage",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="الرافعة المالية"
                    ),
                ),
                (
                    "server_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="اسم الخادم"
                    ),
                ),
                (
                    "is_connected",
                    models.BooleanField(default=False, verbose_name="متصل"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "نشط"),
                            ("inactive", "غير نشط"),
                            ("suspended", "موقوف"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trading_accounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "حساب تداول",
                "verbose_name_plural": "حسابات التداول",
            },
        ),
        migrations.AddField(
            model_name="trade",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trades",
                to="trading.tradingaccount",
                verbose_name="حساب التداول",
            ),
        ),
        migrations.CreateModel(
            name="RiskSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "risk_per_trade",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        max_digits=5,
                        verbose_name="نسبة المخاطرة لكل صفقة",
                    ),
                ),
                (
                    "daily_loss_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="الحد اليومي للخسارة",
                    ),
                ),
                (
                    "max_open_trades",
                    models.PositiveIntegerField(
                        default=3, verbose_name="أقصى عدد صفقات مفتوحة"
                    ),
                ),
                (
                    "position_size_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        max_digits=10,
                        verbose_name="الحد الأقصى لحجم الصفقة",
                    ),
                ),
                (
                    "stop_loss_required",
                    models.BooleanField(
                        default=True, verbose_name="إلزامية وقف الخسارة"
                    ),
                ),
                (
                    "allow_weekend_holding",
                    models.BooleanField(
                        default=False,
                        verbose_name="السماح بالاحتفاظ لعطلة نهاية الأسبوع",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_settings",
                        to="trading.tradingaccount",
                        verbose_name="حساب التداول",
                    ),
                ),
            ],
            options={
                "verbose_name": "إعدادات المخاطر",
                "verbose_name_plural": "إعدادات المخاطر",
            },
        ),
        migrations.CreateModel(
            name="PerformanceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_period",
                    models.CharField(max_length=50, verbose_name="الفترة"),
                ),
                (
                    "total_trades",
                    models.PositiveIntegerField(
                        default=0, verbose_name="إجمالي الصفقات"
                    ),
                ),
                (
                    "win_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="نسبة الربح",
                    ),
                ),
                (
                    "net_profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="صافي الربح",
                    ),
                ),
                (
                    "max_drawdown",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="أقصى تراجع",
                    ),
                ),
                (
                    "report_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="بيانات التقرير"
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_reports",
                        to="trading.tradingaccount",
                        verbose_name="حساب التداول",
                    ),
                ),
            ],
            options={
                "verbose_name": "تقرير أداء",
                "verbose_name_plural": "تقارير الأداء",
            },
        ),
    ]
