# Generated by Django 5.2.13 on 2026-04-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_timezone_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_email_verified",
            field=models.BooleanField(
                default=False, verbose_name="تم تأكيد البريد الإلكتروني"
            ),
        ),
    ]
